# Databricks notebook source
# MAGIC %md
# MAGIC # TCGA Ovarian Cancer Clinical Data 
# MAGIC ## Sample Analysis in Databricks R notebook: Missing Data, Imputation and Correlation Analysis

# COMMAND ----------

# MAGIC %md
# MAGIC #### Abstract
# MAGIC * ##### Objective
# MAGIC The objective of this analysis is to do a correlation analysis on some of the variables of the TCGA Ovarian Cancer data to explore any substantiative positive or negative correlations between them. When you have multiple variables in your data, which is usually the case, it makes sense to visualise the correlations by using a heatmap of the correlation matrix.
# MAGIC * ##### Methods
# MAGIC Dummy variables are created for all the categorical variables. After this, the missing data is imputed using multiple imputation by chained equations. Then a correlation matrix is generated by Pearson's correlation and the same is visualised using a heatmap. The colors of the heatmap depend on the value of the correlation between the concerned two variables in that cell. 
# MAGIC * ##### Conclusion
# MAGIC The correlation analysis shows that there is relatively good positive correlation between PFS_MONTHS and OS_DAYS, OS_DAYS and OS_MONTHS. This is expected as all these variables denote survival times. There is a negative correlation between survival indicators (PFS and OS) and resistance to platinum containing anticancer drugs. This is also expected as people who are resistant to platinum based antineoplastic drugs are prone to have poorer prognosis than those who are sensitive to it. There is also positive correlation between sensitivity to platinum based antineoplastic drugs and survival times.

# COMMAND ----------

# MAGIC %md
# MAGIC Load required R libraries

# COMMAND ----------

library("plyr")
install.packages("mlr")
library("mlr")
install.packages("VIM")
library("VIM")
install.packages("corrplot")
library("corrplot")
install.packages("mice")
library("mice")
install.packages("psych")
library("psych")

# COMMAND ----------

# MAGIC %md
# MAGIC Load the TCGA Clinical Data into the Databricks cluster R memory

# COMMAND ----------

datClinical <- read.csv("/dbfs//FileStore//tables//4j2ceagn1483424639084/TCGA_OvCa_Clinical.csv", na.strings=c(""," "))

# COMMAND ----------

# MAGIC %md
# MAGIC Load the TCGA Additional Data into Databricks cluster R memory

# COMMAND ----------

datAdditional <- read.csv("/dbfs//FileStore//tables//4j2ceagn1483424639084/TCGA_OvCa_Additional.csv", na.strings=c("", " " ))

# COMMAND ----------

sum(is.na(datClinical))

# COMMAND ----------

# MAGIC %md
# MAGIC View the column/field names of the loaded data

# COMMAND ----------

colnames(datClinical)

# COMMAND ----------

# MAGIC %md
# MAGIC Change the column names to a more user friendly format

# COMMAND ----------

colnames(datClinical) = c("PATIENT_ID", "AGE_AT_DX","VITAL_STATUS", "TUMOR_STAGE","TUMOR_GRADE","TUMOR_RESIDUAL_DISEASE","PRIMARY_RX_OUTCOME_SUCCESS","PERSON_NEOPLASM_CANCER_STATUS",
                  "OS_MONTHS","PFS_STATUS","PFS_MONTHS","PLATINUM_FREE_INTERVAL_MONTHS","PLATINUM_STATUS")

# COMMAND ----------

# MAGIC %md
# MAGIC Assign legit datatypes

# COMMAND ----------

datClinical$PLATINUM_STATUS = as.factor(as.character(datClinical$PLATINUM_STATUS))
datClinical$PFS_MONTHS = as.numeric(as.character(datClinical$PFS_MONTHS))
datClinical$OS_MONTHS = as.numeric(as.character(datClinical$OS_MONTHS))

# COMMAND ----------

# MAGIC %md
# MAGIC Select only the observations where platinum status is not missing

# COMMAND ----------

platinum = datClinical[datClinical$PLATINUM_STATUS != "Missing", ]
nrow(platinum)

# COMMAND ----------

# MAGIC %md
# MAGIC Just to show how to convert R DataFrame to a Spark DataFrame

# COMMAND ----------

platinum_SparkDF = createDataFrame(sqlContext, data = platinum)

# COMMAND ----------

# MAGIC %md
# MAGIC Change the column names to a more user friendly format

# COMMAND ----------

colnames(datAdditional)

# COMMAND ----------

colnames(datAdditional) = c("PATIENT_ID", "SAMPLE_BARCODE", "CENTER", "YEAR_DX", "ETHNICITY", "JEWISH_ORIGIN", "OS", "OS_DAYS", "RECURRENCE_STATUS", "DISTANT_RECURRENCE_STATUS",
                            "SURGICAL_OUTCOME", "PHARMACEUTICAL_THERAPY_TYPE", "DRUG_NAME")

# COMMAND ----------

# MAGIC %md
# MAGIC Assign legit datatypes

# COMMAND ----------

datAdditional$OS_DAYS = as.numeric(as.character(datAdditional$OS_DAYS))
datAdditional$ETHNICITY = as.factor(as.character(datAdditional$ETHNICITY))

# COMMAND ----------

# MAGIC %md
# MAGIC Remove duplicate rows

# COMMAND ----------

datAdditional = datAdditional[!duplicated(datAdditional$PATIENT_ID),]

# COMMAND ----------

# MAGIC %md
# MAGIC Do an inner join of TCGA Clinical and Additional datasets

# COMMAND ----------

dat = plyr::join(datAdditional, datClinical, type="inner")

# COMMAND ----------

dim(dat)

# COMMAND ----------

# MAGIC %md
# MAGIC Assign legit datatypes

# COMMAND ----------

dat$AGE_AT_DX = as.numeric(as.character(dat$AGE_AT_DX))
dat$PFS_MONTHS = as.numeric(as.character(dat$PFS_MONTHS))
dat$OS_MONTHS = as.numeric(as.character(dat$OS_MONTHS))
dat$OS_DAYS = as.numeric(as.character(dat$OS_DAYS))

# COMMAND ----------

sparkDF = createDataFrame(sqlContext, data = dat)

# COMMAND ----------

display(sparkDF)

# COMMAND ----------

# MAGIC %md
# MAGIC Select only the required variables for correlations analysis

# COMMAND ----------

dat = dat[,c("PATIENT_ID","ETHNICITY","OS_DAYS","RECURRENCE_STATUS", "DISTANT_RECURRENCE_STATUS","SURGICAL_OUTCOME",
             "AGE_AT_DX","TUMOR_STAGE","TUMOR_GRADE","OS_MONTHS","PFS_MONTHS","PLATINUM_FREE_INTERVAL_MONTHS","PLATINUM_STATUS")]
dim(dat)

# COMMAND ----------

colnames(dat)

# COMMAND ----------

dat$RECURRENCE_STATUS = as.factor(as.character(dat$RECURRENCE_STATUS))
dat$DISTANT_RECURRENCE_STATUS = as.factor(as.character(dat$DISTANT_RECURRENCE_STATUS))

# COMMAND ----------

# MAGIC %md
# MAGIC Create dummy variables out of the categorical variables in dat

# COMMAND ----------

dummy = createDummyFeatures(dat, cols = c("RECURRENCE_STATUS", "DISTANT_RECURRENCE_STATUS", "SURGICAL_OUTCOME","TUMOR_STAGE",
                                          "TUMOR_GRADE","PLATINUM_STATUS"))
dim(dummy)

# COMMAND ----------

# MAGIC %md
# MAGIC View column names of the dataset with dummy variables

# COMMAND ----------

colnames(dummy)

# COMMAND ----------

# MAGIC %md
# MAGIC There is no need to keep two separate variables for binary categorical variables like RECURRENCE_STATUS, DISTANT_RECURRENCE_STATUS, SURGICAL_OUTCOME. 
# MAGIC Only keep the dummy variable corresponding to ".TRUE" for these. Also removing the TUMOR_GRADE variable.

# COMMAND ----------

dummy = dummy[,-c(4,6,8,18,19)]
dim(dummy)

# COMMAND ----------

colnames(dummy)

# COMMAND ----------

# MAGIC %md
# MAGIC #### Missing Data and Imputation

# COMMAND ----------

# MAGIC %md
# MAGIC How many NA values are there

# COMMAND ----------

sum(is.na(dummy))

# COMMAND ----------

intelData = dummy[,-c(1,2)] #omitting PATIENT_ID and ETHNICITY as it is not used for correlation

# COMMAND ----------

# MAGIC %md
# MAGIC A visual representation of the missing data

# COMMAND ----------

plotMissingData <- aggr(intelData, col=c('navyblue','red'), 
                        numbers=TRUE, sortVars=TRUE, labels=names(intelData), cex.axis=.7, 
                        gap=3, ylab=c("Histogram of missing data","Pattern"))

# COMMAND ----------

# MAGIC %md
# MAGIC The above plot shows that 57.63% of the observations (intelData) has no missing values. The output shown below shows the number of missing values in each of the fields of intelData. You can see that PLATINUM_FREE_INTERVAL_MONTHS has 105 missing values and PFS_MONTHS has 69 values.

# COMMAND ----------

plotMissingData$missings

# COMMAND ----------

# MAGIC %md
# MAGIC Impute the missing values using MICE. MICE is a technique for Multiple Imputations by Chained Equations. This will impute the missing values based on predictive regression analysis.

# COMMAND ----------

imp = mice(intelData, m = 1,
           maxit = 50,
           meth = 'pmm',
           seed = 500)

# COMMAND ----------

# MAGIC %md
# MAGIC Create the dataset with imputed values

# COMMAND ----------

comp <- mice::complete(imp, 1)
dim(comp)

# COMMAND ----------

display(comp)

# COMMAND ----------

# MAGIC %md
# MAGIC Just to confirm the dataset has no missing values

# COMMAND ----------

plotImputedDataSet <- aggr(comp, col=c('navyblue','red'), 
                  numbers=TRUE, sortVars=TRUE, labels=names(comp), cex.axis=.7, 
                  gap=3, ylab=c("Histogram of missing data","Pattern"))

# COMMAND ----------

# MAGIC %md
# MAGIC The above plot simply tells that all the missing values have been imputed. We will be doing the correlation analysis on this imputed data.

# COMMAND ----------

# MAGIC %md
# MAGIC #### Correlation analysis and plot

# COMMAND ----------

corMat = cor(comp)
corrplot(corMat,
         order = "hclust",
         method = "circle",
         tl.cex = .7,
         mar=c(1,2,3,1))

# COMMAND ----------

# MAGIC %md
# MAGIC The above correlation plot shows that there is relatively good positive correlation between PFS_MONTHS and OS_DAYS, OS_DAYS and OS_MONTHS. There is a negative correlation between survival indicators (PFS and OS) and resistance to platinum containing anticancer drugs. 

# COMMAND ----------

# MAGIC %md
# MAGIC Scatter Plot of Matrices

# COMMAND ----------

pairs.panels(comp,
             pch='.',
             gap=1,
             ellipses=T,
             hist.col='lavender',
             col="blue",
             lwd=2)

# COMMAND ----------

# MAGIC %md
# MAGIC The above plot shows the correlation values above the diagnonal and scatterplot of the variables below the diagonal. This is just another way of visualising correlation matrix

# COMMAND ----------

library("MASS")

# COMMAND ----------

parcoord(comp[,c(17,1,4,3,13)], col=rainbow(length(comp[,1])), var.label=TRUE,
        main = "Parallel Coordinates")

# COMMAND ----------



# COMMAND ----------



# COMMAND ----------



# COMMAND ----------

colnames(comp)