# Databricks notebook source
# MAGIC %md
# MAGIC ## TCGA Ovarian Cancer Clinical Data
# MAGIC ### Sample Analysis in PYTHON notebook: Correlation Analysis
# MAGIC #### Author: PINAKI BISWAS

# COMMAND ----------

# MAGIC %md
# MAGIC #### Abstract
# MAGIC * ##### Objective
# MAGIC The objective of this analysis is to do a correlation analysis on some of the variables of the TCGA Ovarian Cancer data to explore any substantiative positive or negative correlations between them. When you have multiple variables in your data, which is usually the case, it makes sense to visualise the correlations by using a heatmap of the correlation matrix.
# MAGIC * ##### Methods
# MAGIC Dummy variables are created for all the categorical variables. After this, the missing data is imputed using multiple imputation by chained equations. The imputed data is imported into this Python notebook (imputations and creation of dummy variables are done in R).
# MAGIC Then a correlation matrix is generated by Pearson's correlation and the same is visualised using a heatmap. The colors of the heatmap depend on the value of the correlation between the concerned two variables in that cell. 
# MAGIC * ##### Conclusion
# MAGIC The correlation analysis shows that there is relatively good positive correlation between PFS_MONTHS and OS_DAYS, OS_DAYS and OS_MONTHS. This is expected as all these variables denote survival times. There is a negative correlation between survival indicators (PFS and OS) and resistance to platinum containing anticancer drugs. This is also expected as people who are resistant to platinum based antineoplastic drugs are prone to have poorer prognosis than those who are sensitive to it. There is also positive correlation between sensitivity to platinum based antineoplastic drugs and survival times.

# COMMAND ----------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm
from pandas.tools.plotting import scatter_matrix

# COMMAND ----------

# MAGIC %md
# MAGIC Load the imputed dataset as pandas dataframes

# COMMAND ----------

dat = pd.read_csv("/dbfs//FileStore//tables//wszubvdn1483698733469/imputedDataset.csv")
print dat.shape

# COMMAND ----------

# MAGIC %md
# MAGIC How many missing values

# COMMAND ----------

 dat.isnull().values.sum()

# COMMAND ----------

# MAGIC %md
# MAGIC Dimensions

# COMMAND ----------

dat.shape

# COMMAND ----------

# MAGIC %md
# MAGIC Compute correlation matrix

# COMMAND ----------

corr_mat = dat.corr()

# COMMAND ----------

print corr_mat

# COMMAND ----------

fig = plt.figure(figsize=(12,14))

sns.heatmap(corr_mat, square=True)
plt.yticks(rotation=0)
plt.xticks(rotation=90)

display(fig)

# COMMAND ----------

# MAGIC  %md
# MAGIC * ##### Results:
# MAGIC  
# MAGIC The above visualisation is the correlation matrix heatmap output generated in Python. There is a good positive correlation among OS_DAYS, OS_MONTHS and PFS_MONTHS which is naturally expected. There is also a positive correlation between OS_DAYS and PLATINUM_STATUS_Sensitive _which translates to the inference that subjects who are sensitive to platinum containing anticancer drugs have more survival. This is something which we would expect and the Boxplot with ANOVA confirmed the inference. It is to be noted that correlation analysis heatmap is an exploratory guide to find associations between different variables in your data. For confirming the statistical significance you would normally resort later to inferential statistical tests such as ANOVA.