# Databricks notebook source
# MAGIC %md 
# MAGIC 
# MAGIC See delta documentation: https://docs.databricks.com/delta/delta-intro.html

# COMMAND ----------

# MAGIC %sql 
# MAGIC DROP TABLE IF EXISTS ASSOCIATION_OSS_CELL_INFO;
# MAGIC 
# MAGIC CREATE TABLE ASSOCIATION_OSS_CELL_INFO(
# MAGIC 	oss_cell_info_id int COMMENT 'NOT NULL',
# MAGIC 	site_cd String COMMENT 'NOT NULL',
# MAGIC 	sector_cd String COMMENT 'NOT NULL',
# MAGIC 	sector_technology_desc String COMMENT 'NOT NULL',
# MAGIC 	oss_vendor String COMMENT 'NOT NULL',
# MAGIC 	source_oss_server_desc String ,
# MAGIC 	network_hierarchy String ,
# MAGIC 	oss_site_name String COMMENT 'NOT NULL',
# MAGIC 	oss_sector_name String ,
# MAGIC 	oss_cell_name String ,
# MAGIC 	oss_parent_equip_cd String ,
# MAGIC 	parent_equip_cd String ,
# MAGIC 	parent_equip_type_desc String COMMENT 'NOT NULL',
# MAGIC 	oss_cgi String ,
# MAGIC 	oss_mcc String ,
# MAGIC 	oss_mnc String ,
# MAGIC 	oss_lac String ,
# MAGIC 	oss_cell_id String ,
# MAGIC 	cell_operational_state_desc String ,
# MAGIC 	cell_administration_state_desc String ,
# MAGIC 	cell_barred_state_desc String ,
# MAGIC 	sector_status_desc String COMMENT 'NOT NULL',
# MAGIC 	sector_status_rank_preference String COMMENT 'NOT NULL',
# MAGIC 	oss_parent_obj_cd String ,
# MAGIC 	oss_parent_obj_type_desc String COMMENT 'NOT NULL',
# MAGIC 	oss_site_equip_cd String ,
# MAGIC 	oss_site_equip_type_desc String COMMENT 'NOT NULL',
# MAGIC 	oss_parent_equip_mkt_cd String ,
# MAGIC 	oss_mkt_name String COMMENT 'NOT NULL',
# MAGIC 	reason_desc String ,
# MAGIC 	alarm_text String ,
# MAGIC 	last_sync_dt timestamp COMMENT 'NOT NULL',
# MAGIC 	test_cell_flg String COMMENT 'NOT NULL',
# MAGIC 	source_created_by_id String COMMENT 'NOT NULL',
# MAGIC 	source_created_dt timestamp COMMENT 'NOT NULL',
# MAGIC 	source_modified_by_id String COMMENT 'NOT NULL',
# MAGIC 	source_modified_dt timestamp ,
# MAGIC 	nortel_site_cd String ,
# MAGIC 	oss_enodeb_id String ,
# MAGIC 	oss_tac String ,
# MAGIC 	oss_pci String ,
# MAGIC 	oss_ecgi String ,
# MAGIC 	node_type_desc String 
# MAGIC 	)
# MAGIC 	USING delta 
# MAGIC     OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/ASSOCIATION_OSS_CELL_INFO_delta' )

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS dim_sector;
# MAGIC 
# MAGIC CREATE TABLE dim_sector(
# MAGIC 	sector_dwkey bigint COMMENT 'Not Null',
# MAGIC 	sector_cd String ,
# MAGIC 	site_cd String COMMENT 'Not Null',
# MAGIC 	site_dwkey bigint COMMENT 'Not Null',
# MAGIC 	asset_sector_type_cd String ,
# MAGIC 	eirp float ,
# MAGIC 	sector_lat decimal(15, 10) ,
# MAGIC 	sector_long decimal(15, 10) ,
# MAGIC 	sector_lat_long_method_desc String ,
# MAGIC 	pa_power float ,
# MAGIC 	sector_technology_desc String ,
# MAGIC 	source_sector_id int COMMENT 'Not Null',
# MAGIC 	sourcing_system_cd smallint COMMENT 'Not Null',
# MAGIC 	created_by_id String COMMENT 'Not Null',
# MAGIC 	created_dt timestamp COMMENT 'Not Null',
# MAGIC 	modified_by_id String COMMENT 'Not Null',
# MAGIC 	modified_dt timestamp COMMENT 'Not Null',
# MAGIC 	sector_status String ,
# MAGIC 	cvrg_type String ,
# MAGIC 	active_flg string ,
# MAGIC 	virtual_config_item String ,
# MAGIC 	sector_on_air_dt timestamp ,
# MAGIC 	sector_on_air_status String ,
# MAGIC 	sector_off_air_dt timestamp ,
# MAGIC 	sector_off_air_status String ,
# MAGIC 	small_cell_flg smallint ,
# MAGIC 	rfp_drv_enodeb_id String ,
# MAGIC 	nodebname String ,
# MAGIC 	sector_official_on_air_dt timestamp ,
# MAGIC 	sector_official_off_air_dt timestamp ,
# MAGIC 	area_id String 
# MAGIC )
# MAGIC USING parquet 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/dim_sector_parquet' )

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS dim_site;
# MAGIC 
# MAGIC CREATE TABLE dim_site(
# MAGIC 	site_dwkey bigint COMMENT 'Not Null',
# MAGIC 	site_cd String COMMENT 'Not Null',
# MAGIC 	site_name String ,
# MAGIC 	bta_cd smallint COMMENT 'Not Null',
# MAGIC 	bta_name String COMMENT 'Not Null',
# MAGIC 	build_status_cd smallint COMMENT 'Not Null',
# MAGIC 	build_status_desc String COMMENT 'Not Null',
# MAGIC 	jurisdiction_cd int COMMENT 'Not Null',
# MAGIC 	jurisdiction_name String COMMENT 'Not Null',
# MAGIC 	site_class_cd smallint COMMENT 'Not Null',
# MAGIC 	site_class_desc String COMMENT 'Not Null',
# MAGIC 	site_lat_long_format_cd smallint COMMENT 'Not Null',
# MAGIC 	site_lat_long_format_desc String COMMENT 'Not Null',
# MAGIC 	site_lat_long_method_cd smallint COMMENT 'Not Null',
# MAGIC 	site_lat_long_method_desc String COMMENT 'Not Null',
# MAGIC 	site_mkt_cd String COMMENT 'Not Null',
# MAGIC 	site_mkt_name String COMMENT 'Not Null',
# MAGIC 	site_state_cd int COMMENT 'Not Null',
# MAGIC 	site_state_name String COMMENT 'Not Null',
# MAGIC 	site_status_cd smallint COMMENT 'Not Null',
# MAGIC 	site_status_desc String COMMENT 'Not Null',
# MAGIC 	site_subclass_cd int COMMENT 'Not Null',
# MAGIC 	site_subclass_desc String COMMENT 'Not Null',
# MAGIC 	site_submkt_cd String COMMENT 'Not Null',
# MAGIC 	site_submkt_name String COMMENT 'Not Null',
# MAGIC 	site_technology_type_cd smallint COMMENT 'Not Null',
# MAGIC 	site_technology_type_desc String COMMENT 'Not Null',
# MAGIC 	site_type_cd smallint COMMENT 'Not Null',
# MAGIC 	site_type_desc String COMMENT 'Not Null',
# MAGIC 	agl float ,
# MAGIC 	available_agls_desc String ,
# MAGIC 	can_mkt_site_flg smallint ,
# MAGIC 	ground_amsl float ,
# MAGIC 	neighborhood_desc String ,
# MAGIC 	non_standard_site String ,
# MAGIC 	raw_land_flg smallint COMMENT 'Not Null',
# MAGIC 	site_lat decimal(10, 8) COMMENT 'Not Null',
# MAGIC 	site_long decimal(11, 8) COMMENT 'Not Null',
# MAGIC 	site_on_air_dt timestamp ,
# MAGIC 	site_off_air_dt timestamp ,
# MAGIC 	structure_capacity String ,
# MAGIC 	structure_ht float ,
# MAGIC 	switch_on_air_dt timestamp ,
# MAGIC 	aws_spectrum_id smallint ,
# MAGIC 	element_class String ,
# MAGIC 	tax_assessor_number String ,
# MAGIC 	temp_install_flg smallint COMMENT 'Not Null',
# MAGIC 	nlp_phase int ,
# MAGIC 	nlp_priority int ,
# MAGIC 	nlp_desc String ,
# MAGIC 	nlp_desc_active_flg string ,
# MAGIC 	traffic_count decimal(38, 20) ,
# MAGIC 	load_dt timestamp ,
# MAGIC 	row_effective_begin_dt timestamp ,
# MAGIC 	row_effective_end_dt timestamp ,
# MAGIC 	row_active_flg string ,
# MAGIC 	source_active_flg tinyint COMMENT 'Not Null',
# MAGIC 	source_location_id bigint COMMENT 'Not Null',
# MAGIC 	source_ring_id bigint ,
# MAGIC 	source_site_id bigint COMMENT 'Not Null',
# MAGIC 	source_site_mkt_id smallint ,
# MAGIC 	source_site_submkt_id smallint ,
# MAGIC 	source_created_by_id String COMMENT 'Not Null',
# MAGIC 	source_created_dt timestamp COMMENT 'Not Null',
# MAGIC 	source_modified_by_id String ,
# MAGIC 	source_modified_dt timestamp ,
# MAGIC 	sourcing_system_cd smallint COMMENT 'Not Null',
# MAGIC 	created_by_id String COMMENT 'Not Null',
# MAGIC 	created_dt timestamp COMMENT 'Not Null',
# MAGIC 	modified_by_id String COMMENT 'Not Null',
# MAGIC 	modified_dt timestamp COMMENT 'Not Null',
# MAGIC 	rf_dt timestamp ,
# MAGIC 	rf_status_desc String ,
# MAGIC 	gsm_status_desc String ,
# MAGIC 	umts_status_desc String ,
# MAGIC 	hspa_status_desc String ,
# MAGIC 	lte_status_desc String ,
# MAGIC 	uma_status_desc String ,
# MAGIC 	other_technology_status_desc String ,
# MAGIC 	lmu_id int ,
# MAGIC 	site_priority_desc String ,
# MAGIC 	corenet_vlan_id smallint ,
# MAGIC 	corenet_ip_addr String ,
# MAGIC 	nmnet_vlan smallint ,
# MAGIC 	nmnet_base_ip_addr String ,
# MAGIC 	nmnet_ip_addr String ,
# MAGIC 	csr_oam_ip_addr String ,
# MAGIC 	backhaul_type String ,
# MAGIC 	backhaul_type_activation_dt timestamp ,
# MAGIC 	achievable_cir smallint ,
# MAGIC 	daily_traffic_count decimal(38, 20) ,
# MAGIC 	battery_power_type_desc String ,
# MAGIC 	fixed_gen_fuel_cell_hours smallint ,
# MAGIC 	gsm_battery_hours smallint ,
# MAGIC 	umts_battery_hours smallint ,
# MAGIC 	gsm_transport_type_desc String ,
# MAGIC 	umts_transport_type_desc String ,
# MAGIC 	backup_power_type_desc String ,
# MAGIC 	growth_site_flg string ,
# MAGIC 	lmu_vendor_desc String ,
# MAGIC 	gsm_site_on_air_dt timestamp ,
# MAGIC 	umts_site_on_air_dt timestamp ,
# MAGIC 	lte_site_on_air_dt timestamp ,
# MAGIC 	gsm_site_off_air_dt timestamp ,
# MAGIC 	umts_site_off_air_dt timestamp ,
# MAGIC 	lte_site_off_air_dt timestamp ,
# MAGIC 	msa_desc String ,
# MAGIC 	cdma_site_on_air_dt timestamp ,
# MAGIC 	cdma_site_off_air_dt timestamp ,
# MAGIC 	wls_id String ,
# MAGIC 	subscribers_per_day int ,
# MAGIC 	spectrum_type String ,
# MAGIC 	l700_site_on_air_dt timestamp ,
# MAGIC 	l700_site_off_air_dt timestamp ,
# MAGIC 	l1900_site_on_air_dt timestamp ,
# MAGIC 	l1900_site_off_air_dt timestamp ,
# MAGIC 	l2100_site_on_air_dt timestamp ,
# MAGIC 	l2100_site_off_air_dt timestamp ,
# MAGIC 	on_air_indicator_cd String ,
# MAGIC 	structure_vendor_desc String ,
# MAGIC 	structure_vendor_role_desc String ,
# MAGIC 	structure_vendor_code_desc String ,
# MAGIC 	previous_structure_vendor_desc String ,
# MAGIC 	structure_lease_term_start_dt timestamp ,
# MAGIC 	structure_lease_term_end_dt timestamp ,
# MAGIC 	structure_initial_lease_term_start_dt timestamp ,
# MAGIC 	structure_lease_final_end_dt timestamp ,
# MAGIC 	structure_annual_rent decimal(19, 2) ,
# MAGIC 	structure_rent_increase_dt timestamp ,
# MAGIC 	structure_rent_increase_type_desc String ,
# MAGIC 	structure_rent_increase_percent String ,
# MAGIC 	structure_rent_increase_period String ,
# MAGIC 	structure_govern_doc_assign_sublet String ,
# MAGIC 	structure_govern_doc_equip_modifications String ,
# MAGIC 	structure_govern_doc_termination_rights String ,
# MAGIC 	ground_vendor_desc String ,
# MAGIC 	ground_vendor_role_desc String ,
# MAGIC 	ground_vendor_code String ,
# MAGIC 	previous_ground_vendor_desc String ,
# MAGIC 	ground_lease_term_start_dt timestamp ,
# MAGIC 	ground_lease_term_end_dt timestamp ,
# MAGIC 	ground_initial_lease_term_start_dt timestamp ,
# MAGIC 	ground_lease_final_end_dt timestamp ,
# MAGIC 	ground_annual_rent decimal(19, 2) ,
# MAGIC 	ground_rent_increase_dt timestamp ,
# MAGIC 	ground_rent_increase_type_desc String ,
# MAGIC 	ground_rent_increase_percent String ,
# MAGIC 	ground_rent_increase_period String ,
# MAGIC 	ground_govern_doc_assign_sublet String ,
# MAGIC 	ground_govern_doc_equip_modifications String ,
# MAGIC 	ground_govern_doc_termination_rights String ,
# MAGIC 	property_vendor_source_modified_dt timestamp ,
# MAGIC 	override_ind smallint ,
# MAGIC 	tower_top_configuration_desc String ,
# MAGIC 	umts_1900_site_on_air_dt timestamp ,
# MAGIC 	umts_1900_site_off_air_dt timestamp ,
# MAGIC 	umts_2100_site_on_air_dt timestamp ,
# MAGIC 	umts_2100_site_off_air_dt timestamp ,
# MAGIC 	umts_on_air_indicator_cd String ,
# MAGIC 	build_to_suit_desc String ,
# MAGIC 	cptl_lease_eligible String ,
# MAGIC 	cptl_lease_qualified String ,
# MAGIC 	assigned_traunch String ,
# MAGIC 	assigned_po_number String ,
# MAGIC 	cptl_lease_executed_dt timestamp ,
# MAGIC 	paint_the_map_site_flg String ,
# MAGIC 	paint_the_map_priority_desc String ,
# MAGIC 	paint_the_map_square_miles String ,
# MAGIC 	metro_site_flg string ,
# MAGIC 	host_site_cd String ,
# MAGIC 	l850_site_on_air_dt timestamp ,
# MAGIC 	l850_site_off_air_dt timestamp ,
# MAGIC 	hp_flg String ,
# MAGIC 	small_maintenance_desc String ,
# MAGIC 	small_cell_umts_validation_desc String ,
# MAGIC 	small_cell_maintenance_desc String ,
# MAGIC 	aav_upgrade_ordered_dt timestamp ,
# MAGIC 	aav_upgrade_ordered_status_desc String ,
# MAGIC 	aav_upgrade_complete_dt timestamp ,
# MAGIC 	aav_upgrade_complete_status String ,
# MAGIC 	reqd_cir int ,
# MAGIC 	transport_upgrade_reqd_desc String ,
# MAGIC 	transport_upgrade_dependency_desc String ,
# MAGIC 	l700_priority_flg String ,
# MAGIC 	l1900_priority_flg String ,
# MAGIC 	l700_congestion_priority_period String ,
# MAGIC 	l1900_congestion_priority_period String ,
# MAGIC 	on_lease_program_flg string ,
# MAGIC 	lease_id String ,
# MAGIC 	lease_program_desc String ,
# MAGIC 	ookla_priority tinyint ,
# MAGIC 	platinum_site_flg String ,
# MAGIC 	platinum_cluster_id String ,
# MAGIC 	csne_retail_high_risk_por_flg String ,
# MAGIC 	csne_coverage_flg String ,
# MAGIC 	l2100_aws3_site_on_air_dt timestamp ,
# MAGIC 	l2100_aws3_site_off_air_dt timestamp ,
# MAGIC 	lte_unlicensed_site_on_air_dt timestamp ,
# MAGIC 	lte_unlicensed_site_off_air_dt timestamp ,
# MAGIC 	l2100_aws3_on_air_proj_cd String ,
# MAGIC 	lte_unlicensed_onair_proj_cd String ,
# MAGIC 	cmg_aav_vettingresult_desc String ,
# MAGIC 	l600_site_on_air_dt timestamp ,
# MAGIC 	l600_site_off_air_dt timestamp ,
# MAGIC 	Store_SAP_ID String ,
# MAGIC 	nbiot_on_air_dt timestamp ,
# MAGIC 	5g_on_air_dt timestamp ,
# MAGIC 	nbiot_off_air_dt timestamp ,
# MAGIC 	5g_off_air_dt timestamp ,
# MAGIC 	t2100_on_air_dt timestamp ,
# MAGIC 	t2100_off_air_dt timestamp ,
# MAGIC 	t1900_on_air_dt timestamp ,
# MAGIC 	t1900_off_air_dt timestamp ,
# MAGIC 	t600_on_air_dt timestamp ,
# MAGIC 	t600_off_air_dt timestamp ,
# MAGIC 	n28_on_air_dt timestamp ,
# MAGIC 	n28_off_air_dt timestamp ,
# MAGIC 	n39_on_air_dt timestamp ,
# MAGIC 	n39_off_air_dt timestamp ,
# MAGIC 	n600_on_air_dt timestamp ,
# MAGIC 	n600_off_air_dt timestamp ,
# MAGIC 	l600_clearing_dt date ,
# MAGIC 	l600_clearing_status String ,
# MAGIC 	l600_transmit_approval_dt date ,
# MAGIC 	l600_transmit_approval_status String ,
# MAGIC 	onair_indicator_5g String ,
# MAGIC 	onair_indicator_nbiot String ,
# MAGIC 	b12_aggregate_interference_5db String ,
# MAGIC 	b12_aggregate_difference_db float ,
# MAGIC 	b12_aggregate_interference_low_date date 
# MAGIC   )
# MAGIC USING parquet 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/dim_site_parquet' )

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table if exists fact_alarm;
# MAGIC 
# MAGIC CREATE TABLE fact_alarm(
# MAGIC 	alarm_dwkey bigint COMMENT 'Not Null',
# MAGIC 	equip_cd String ,
# MAGIC 	mkt_cd String ,
# MAGIC 	region_name String ,
# MAGIC 	manager_desc String ,
# MAGIC 	manager_class_desc String ,
# MAGIC 	mo_desc String ,
# MAGIC 	mo_class_desc String ,
# MAGIC 	technology_desc String ,
# MAGIC 	alarm_number bigint COMMENT 'Not Null',
# MAGIC 	alarm_name String ,
# MAGIC 	alarm_created_dt date COMMENT 'Not Null',
# MAGIC 	alarm_created_full_dt timestamp COMMENT 'Not Null',
# MAGIC 	alarm_cleared_dt date ,
# MAGIC 	alarm_cleared_full_dt timestamp ,
# MAGIC 	last_alarm_dt date COMMENT 'Not Null',
# MAGIC 	last_alarm_full_dt timestamp COMMENT 'Not Null',
# MAGIC 	alarm_acknowledged_by String ,
# MAGIC 	alarm_cleared_by String ,
# MAGIC 	alarm_count int ,
# MAGIC 	alarm_desc String ,
# MAGIC 	source_severity_id tinyint ,
# MAGIC 	source_severity_desc String ,
# MAGIC 	source_ticket_id bigint ,
# MAGIC 	source_fm_system_cd String COMMENT 'Not Null',
# MAGIC 	created_by_id String COMMENT 'Not Null',
# MAGIC 	created_dt timestamp COMMENT 'Not Null',
# MAGIC 	modified_by_id String COMMENT 'Not Null',
# MAGIC 	modified_dt timestamp COMMENT 'Not Null',
# MAGIC 	parent_indicator_flg String ,
# MAGIC 	child_indicator_flg String ,
# MAGIC 	nest_state_desc_at_alarm_creation String ,
# MAGIC 	source_view_type_desc String ,
# MAGIC 	source_modified_dt timestamp ,
# MAGIC 	goldengate_datasource_id bigint ,
# MAGIC 	notification_level_cd String ,
# MAGIC 	notification_level_desc String 
# MAGIC )
# MAGIC USING parquet 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/fact_alarm_parquet' )

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table if exists fact_site_down;
# MAGIC 
# MAGIC CREATE TABLE fact_site_down(
# MAGIC 	site_cd String COMMENT 'Not Null',
# MAGIC 	gsm_status_desc String ,
# MAGIC 	umts_status_desc String ,
# MAGIC 	lte_status_desc String ,
# MAGIC 	gsm_last_sync_dt timestamp ,
# MAGIC 	umts_last_sync_dt timestamp ,
# MAGIC 	lte_last_sync_dt timestamp ,
# MAGIC 	last_gsm_site_down_dt timestamp ,
# MAGIC 	last_gsm_site_up_dt timestamp ,
# MAGIC 	last_umts_site_down_dt timestamp ,
# MAGIC 	last_umts_site_up_dt timestamp ,
# MAGIC 	last_lte_site_down_dt timestamp ,
# MAGIC 	last_lte_site_up_dt timestamp ,
# MAGIC 	last_gsm_site_down_reason_desc String ,
# MAGIC 	last_umts_site_down_reason_desc String ,
# MAGIC 	last_lte_site_down_reason_desc String ,
# MAGIC 	created_dt timestamp COMMENT 'Not Null',
# MAGIC 	created_by_id String COMMENT 'Not Null',
# MAGIC 	modified_dt timestamp COMMENT 'Not Null',
# MAGIC 	modified_by_id String COMMENT 'Not Null',
# MAGIC 	gsm_resolve_unknown_flg string ,
# MAGIC 	umts_resolve_unknown_flg string ,
# MAGIC 	lte_resolve_unknown_flg string ,
# MAGIC 	gsm_not_synced_in_last_1hour_flg string ,
# MAGIC 	umts_not_synced_in_last_1hour_flg string ,
# MAGIC 	lte_not_synced_in_last_1hour_flg string ,
# MAGIC 	gsm_insite_only_on_air_flg string ,
# MAGIC 	umts_insite_only_on_air_flg string ,
# MAGIC 	lte_insite_only_on_air_flg string ,
# MAGIC 	gsm_all_sectors_off_air_flg string ,
# MAGIC 	umts_all_sectors_off_air_flg string ,
# MAGIC 	lte_all_sectors_off_air_flg string ,
# MAGIC 	last_gsm_available_dt timestamp ,
# MAGIC 	last_umts_available_dt timestamp ,
# MAGIC 	last_lte_available_dt timestamp ,
# MAGIC 	gsm_nest_override_flg string ,
# MAGIC 	umts_nest_override_flg string ,
# MAGIC 	lte_nest_override_flg string ,
# MAGIC 	core_site_flg string ,
# MAGIC 	gsm_only_flg string ,
# MAGIC 	umts_only_flg string ,
# MAGIC 	gsm_umts_hybrid_flg string ,
# MAGIC 	hspa_21_on_air_flg string ,
# MAGIC 	pmo_only_flg string ,
# MAGIC 	lte_flg string ,
# MAGIC 	metro_site_flg string ,
# MAGIC 	gsm_oss_vendor String ,
# MAGIC 	umts_oss_vendor String ,
# MAGIC 	lte_oss_vendor String ,
# MAGIC 	gsm_parent_equip_cd String ,
# MAGIC 	umts_parent_equip_cd String ,
# MAGIC 	lte_parent_equip_cd String ,
# MAGIC 	gsm_lte_hybrid_flg string ,
# MAGIC 	umts_lte_hybrid_flg string ,
# MAGIC 	all_technologies_flg string ,
# MAGIC 	official_pmo_site_flg smallint 
# MAGIC     )
# MAGIC USING delta 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/fact_site_down_delta' )

# COMMAND ----------

# MAGIC %sql 
# MAGIC drop table if exists LKP_SITE_MKT;
# MAGIC 
# MAGIC CREATE TABLE LKP_SITE_MKT(
# MAGIC 	site_cd String COMMENT 'Not Null',
# MAGIC 	mkt_cd String COMMENT 'Not Null',
# MAGIC 	mkt_name String COMMENT 'Not Null',
# MAGIC 	region_name String COMMENT 'Not Null',
# MAGIC 	created_dt timestamp COMMENT 'Not Null - originally datetime2(3)',
# MAGIC 	modified_dt timestamp COMMENT 'Not Null - originally datetime2(3)'
# MAGIC )
# MAGIC USING parquet 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/lkp_site_mkt_parquet' )

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS REF_DWH_CGI_SITE_SECTOR_LKP;
# MAGIC 
# MAGIC CREATE TABLE REF_DWH_CGI_SITE_SECTOR_LKP(
# MAGIC 	KEY_CGI_ID int COMMENT 'Not Null',
# MAGIC 	OSS_VENDOR String ,
# MAGIC 	SITE_CD String ,
# MAGIC 	SECTOR_CD String ,
# MAGIC 	OSS_CGI String ,
# MAGIC 	SOURCE_LOOKUP_DESC String ,
# MAGIC 	NETWORK_HIERARCHY String ,
# MAGIC 	CREATED_BY_ID String COMMENT 'Not Null',
# MAGIC 	CREATED_DT timestamp COMMENT 'Not Null',
# MAGIC 	MODIFIED_BY_ID String COMMENT 'Not Null',
# MAGIC 	MODIFIED_DT timestamp COMMENT 'Not Null',
# MAGIC 	ci_mkt_cd String ,
# MAGIC 	site_dwkey bigint ,
# MAGIC 	sector_dwkey bigint 
# MAGIC )
# MAGIC USING parquet 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/ref_dwh_cgi_site_sector_lkp_parquet' )

# COMMAND ----------

# MAGIC %sql 
# MAGIC DROP TABLE IF EXISTS V_DWH_ASSOCIATION_CELL_INFO_PARQUET;
# MAGIC 
# MAGIC CREATE TABLE V_DWH_ASSOCIATION_CELL_INFO_PARQUET(
# MAGIC 	oss_vendor String COMMENT 'Not Null',
# MAGIC 	sector_technology_desc String COMMENT 'Not Null',
# MAGIC 	source_oss_server_desc String ,
# MAGIC 	network_hierarchy String ,
# MAGIC 	oss_site_name String COMMENT 'Not Null',
# MAGIC 	oss_sector_name String ,
# MAGIC 	oss_cell_name String ,
# MAGIC 	oss_parent_equip_cd String ,
# MAGIC 	parent_equip_cd String ,
# MAGIC 	parent_equip_type_desc String COMMENT 'Not Null',
# MAGIC 	oss_cgi String ,
# MAGIC 	oss_mcc String ,
# MAGIC 	oss_mnc String ,
# MAGIC 	oss_lac String ,
# MAGIC 	oss_cell_id String ,
# MAGIC 	cell_operational_state_desc String ,
# MAGIC 	cell_administration_state_desc String ,
# MAGIC 	cell_barred_state_desc String ,
# MAGIC 	sector_status_desc String COMMENT 'Not Null',
# MAGIC 	sector_status_rank_preference String COMMENT 'Not Null',
# MAGIC 	oss_parent_obj_cd String ,
# MAGIC 	oss_parent_obj_type_desc String COMMENT 'Not Null',
# MAGIC 	oss_site_equip_cd String ,
# MAGIC 	oss_site_equip_type_desc String COMMENT 'Not Null',
# MAGIC 	oss_parent_equip_mkt_cd String ,
# MAGIC 	oss_mkt_name String COMMENT 'Not Null',
# MAGIC 	reason_desc String ,
# MAGIC 	alarm_text String ,
# MAGIC 	last_sync_dt timestamp COMMENT 'Not Null',
# MAGIC 	test_cell_flg String COMMENT 'Not Null',
# MAGIC 	source_created_by_id String COMMENT 'Not Null',
# MAGIC 	source_created_dt timestamp COMMENT 'Not Null',
# MAGIC 	source_modified_by_id String COMMENT 'Not Null',
# MAGIC 	source_modified_dt timestamp ,
# MAGIC 	nortel_site_cd String ,
# MAGIC 	oss_enodeb_id String ,
# MAGIC 	oss_tac String ,
# MAGIC 	oss_pci String ,
# MAGIC 	oss_ecgi String ,
# MAGIC 	node_type_desc String 
# MAGIC )
# MAGIC USING parquet 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/V_DWH_ASSOCIATION_CELL_INFO_parquet' )

# COMMAND ----------

# MAGIC %sql 
# MAGIC DROP TABLE IF EXISTS V_DWH_ASSOCIATION_CELL_INFO;
# MAGIC 
# MAGIC CREATE TABLE V_DWH_ASSOCIATION_CELL_INFO(
# MAGIC 	oss_vendor String COMMENT 'Not Null',
# MAGIC 	sector_technology_desc String COMMENT 'Not Null',
# MAGIC 	source_oss_server_desc String ,
# MAGIC 	network_hierarchy String ,
# MAGIC 	oss_site_name String COMMENT 'Not Null',
# MAGIC 	oss_sector_name String ,
# MAGIC 	oss_cell_name String ,
# MAGIC 	oss_parent_equip_cd String ,
# MAGIC 	parent_equip_cd String ,
# MAGIC 	parent_equip_type_desc String COMMENT 'Not Null',
# MAGIC 	oss_cgi String ,
# MAGIC 	oss_mcc String ,
# MAGIC 	oss_mnc String ,
# MAGIC 	oss_lac String ,
# MAGIC 	oss_cell_id String ,
# MAGIC 	cell_operational_state_desc String ,
# MAGIC 	cell_administration_state_desc String ,
# MAGIC 	cell_barred_state_desc String ,
# MAGIC 	sector_status_desc String COMMENT 'Not Null',
# MAGIC 	sector_status_rank_preference String COMMENT 'Not Null',
# MAGIC 	oss_parent_obj_cd String ,
# MAGIC 	oss_parent_obj_type_desc String COMMENT 'Not Null',
# MAGIC 	oss_site_equip_cd String ,
# MAGIC 	oss_site_equip_type_desc String COMMENT 'Not Null',
# MAGIC 	oss_parent_equip_mkt_cd String ,
# MAGIC 	oss_mkt_name String COMMENT 'Not Null',
# MAGIC 	reason_desc String ,
# MAGIC 	alarm_text String ,
# MAGIC 	last_sync_dt timestamp COMMENT 'Not Null',
# MAGIC 	test_cell_flg String COMMENT 'Not Null',
# MAGIC 	source_created_by_id String COMMENT 'Not Null',
# MAGIC 	source_created_dt timestamp COMMENT 'Not Null',
# MAGIC 	source_modified_by_id String COMMENT 'Not Null',
# MAGIC 	source_modified_dt timestamp ,
# MAGIC 	nortel_site_cd String ,
# MAGIC 	oss_enodeb_id String ,
# MAGIC 	oss_tac String ,
# MAGIC 	oss_pci String ,
# MAGIC 	oss_ecgi String ,
# MAGIC 	node_type_desc String 
# MAGIC )
# MAGIC USING delta 
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/V_DWH_ASSOCIATION_CELL_INFO_delta' )

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS fact_site_down_update;
# MAGIC CREATE TABLE `fact_site_down_update` (
# MAGIC                    `site_cd` STRING COMMENT 'Not Null', 
# MAGIC                    `site_dwkey` BIGINT COMMENT 'Not Null', 
# MAGIC                    `gsm_status_desc` STRING, 
# MAGIC                    `umts_status_desc` STRING, 
# MAGIC                    `lte_status_desc` STRING, 
# MAGIC                    `last_gsm_site_down_dt` TIMESTAMP, 
# MAGIC                    `last_gsm_site_down_reason_desc` STRING, 
# MAGIC                    `last_lte_site_down_dt` TIMESTAMP, 
# MAGIC                    `last_lte_site_down_reason_desc` STRING, 
# MAGIC                    `last_umts_site_down_dt` TIMESTAMP, 
# MAGIC                    `last_umts_site_down_reason_desc` STRING, 
# MAGIC                    `last_gsm_site_up_dt` TIMESTAMP, 
# MAGIC                    `last_lte_site_up_dt` TIMESTAMP, 
# MAGIC                    `last_umts_site_up_dt` TIMESTAMP, 
# MAGIC                    `GSM_Resolve_Unknown_Flg` STRING, 
# MAGIC                    `GSM_Not_Synced_In_Last_1Hour_Flg` STRING, 
# MAGIC                    `GSM_Insite_Only_On_Air_Flg` STRING, 
# MAGIC                    `UMTS_Resolve_Unknown_Flg` STRING, 
# MAGIC                    `UMTS_Not_Synced_In_Last_1Hour_Flg` STRING, 
# MAGIC                    `UMTS_Insite_Only_On_Air_Flg` STRING, 
# MAGIC                    `LTE_Resolve_Unknown_Flg` STRING, 
# MAGIC                    `LTE_Not_Synced_In_Last_1Hour_Flg` STRING, 
# MAGIC                    `LTE_Insite_Only_On_Air_Flg` STRING, 
# MAGIC                    `GSM_LAST_SYNC_DT` TIMESTAMP, 
# MAGIC                    `UMTS_LAST_SYNC_DT` TIMESTAMP, 
# MAGIC                    `LTE_LAST_SYNC_DT` TIMESTAMP, 
# MAGIC                    `gsm_sector_off` BOOLEAN, 
# MAGIC                    `umts_sector_off` BOOLEAN, 
# MAGIC                    `lte_sector_off` BOOLEAN, 
# MAGIC                    `last_gsm_available_dt` TIMESTAMP, 
# MAGIC                    `last_umts_available_dt` TIMESTAMP, 
# MAGIC                    `last_lte_available_dt` TIMESTAMP)
# MAGIC USING delta
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/fact_site_down_update_delta' )

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS fact_site_down_update_csv;
# MAGIC CREATE TABLE `fact_site_down_update_csv` (
# MAGIC                    `site_cd` STRING COMMENT 'Not Null', 
# MAGIC                    `site_dwkey` BIGINT COMMENT 'Not Null', 
# MAGIC                    `gsm_status_desc` STRING, 
# MAGIC                    `umts_status_desc` STRING, 
# MAGIC                    `lte_status_desc` STRING, 
# MAGIC                    `last_gsm_site_down_dt` TIMESTAMP, 
# MAGIC                    `last_gsm_site_down_reason_desc` STRING, 
# MAGIC                    `last_lte_site_down_dt` TIMESTAMP, 
# MAGIC                    `last_lte_site_down_reason_desc` STRING, 
# MAGIC                    `last_umts_site_down_dt` TIMESTAMP, 
# MAGIC                    `last_umts_site_down_reason_desc` STRING, 
# MAGIC                    `last_gsm_site_up_dt` TIMESTAMP, 
# MAGIC                    `last_lte_site_up_dt` TIMESTAMP, 
# MAGIC                    `last_umts_site_up_dt` TIMESTAMP, 
# MAGIC                    `GSM_Resolve_Unknown_Flg` STRING, 
# MAGIC                    `GSM_Not_Synced_In_Last_1Hour_Flg` STRING, 
# MAGIC                    `GSM_Insite_Only_On_Air_Flg` STRING, 
# MAGIC                    `UMTS_Resolve_Unknown_Flg` STRING, 
# MAGIC                    `UMTS_Not_Synced_In_Last_1Hour_Flg` STRING, 
# MAGIC                    `UMTS_Insite_Only_On_Air_Flg` STRING, 
# MAGIC                    `LTE_Resolve_Unknown_Flg` STRING, 
# MAGIC                    `LTE_Not_Synced_In_Last_1Hour_Flg` STRING, 
# MAGIC                    `LTE_Insite_Only_On_Air_Flg` STRING, 
# MAGIC                    `GSM_LAST_SYNC_DT` TIMESTAMP, 
# MAGIC                    `UMTS_LAST_SYNC_DT` TIMESTAMP, 
# MAGIC                    `LTE_LAST_SYNC_DT` TIMESTAMP, 
# MAGIC                    `gsm_sector_off` BOOLEAN, 
# MAGIC                    `umts_sector_off` BOOLEAN, 
# MAGIC                    `lte_sector_off` BOOLEAN, 
# MAGIC                    `last_gsm_available_dt` DATE, 
# MAGIC                    `last_umts_available_dt` DATE, 
# MAGIC                    `last_lte_available_dt` DATE)
# MAGIC USING csv
# MAGIC OPTIONS (path = 'dbfs:/mnt/ndwpocdl/serving/fact_site_down_update_csv' )